### ISSUE TITLE
Still have the iOS app?

### ISSUE THREAD

**Issue by dcramps** [Hendrik44/flowmotion-one-reloaded#1]
Do you still have a copy of the IPA file for the original app? My phone offloaded it and it's no longer in the store so I can't get it back.

**Comment by Hendrik44** [comment]
Yes I have the IPA File for App version 1.8.2. You can get it here: [https://ufile.io/o1b05kw2](https://ufile.io/o1b05kw2)

**Comment by czj9981** [comment]
Do you still have a copy of the IPA file for the original app? My phone offloaded it and it's no longer in the store so I can't get it back.

**Comment by czj9981** [comment]
I also need this flowmotion app 1.8.2.ipa

**Comment by c0sm0s101** [comment]
Any chance @Hendrik44 you still have it? jumping back to iOS
